sudo: required

services:
  - docker

env:
  - TEST_OS=centos6
  - TEST_JDK=openjdk
  - TEST_JDK=oraclejdk

before_install:
  - docker build -t test/cld:${TEST_OS}-${TEST_JDK} -f tests/Dockerfile.${TEST_OS}.${TEST_JDK} .

script:
  - docker run -it --rm test/cld:${TEST_OS}-${TEST_JDK} /bin/bash -c "cd /opt/cld/ports/java && mvn test"
